version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  # Raise pull requests for version updates
  # to pip against the `develop` branch
  target-branch: "develop"
