version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  commands:
    - uv sync --all-extras
    - uv run sphinx-build -b html docs docs/_build/html

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub
