line-length = 132
target-version = "py312"
fix = true
exclude = ["docs", "tests"]

[lint]
select = ["E","F","I"]
ignore = []

[lint.isort]
known-first-party = ["trnsystor"]
combine-as-imports = true

[lint.per-file-ignores]
"tests/*" = ["ANN"]
